logging.level.org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
server:
  port: 8080
#spring:
#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          issuer-uri: http://www.konradboniecki.com.pl:5000/auth/realms/master
#          jwk-set-uri: http://www.konradboniecki.com.pl:5000/auth/realms/master/protocol/openid-connect/certs

